### ISSUE TITLE
unkown bug: __SOCIAL_IMAGE__ as enctxt in gif generation??

### ISSUE THREAD

**Issue by kupad** [kupad/meme-it-so#51]
```
2021-04-23 09:13:00,954 DEBUG: generating gif...
2021-04-23 09:15:01,833 DEBUG: enctxt __SOCIAL_IMAGE__
2021-04-23 09:15:01,835 ERROR: Exception on /api/gif/ep/S07E06/17244.17358.gif [GET]
Traceback (most recent call last):
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/memeitso/venv/lib/python3.7/site-packages/memeitso_server/gif.py", line 53, in generate_gif
    txt = urllib.parse.unquote(base64.urlsafe_b64decode(enctxt).decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by kupad** [comment]
Not sure why this would happen. But I should catch any enc errors, and at least render a gif without the text if something like this happens. (Logging the error, of course)
